# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=white'

DEFAULT_USER=`whoami`
prompt_context(){}

ENABLE_CORRECTION="true"

plugins=(git zsh-autosuggestions ssh-agent colored-man-pages)

zstyle :omz:plugins:ssh-agent identities id_ed25519

source $ZSH/oh-my-zsh.sh

# User configuration

export LANG=en_US.UTF-8
export LC=C
export EDITOR='vim'

alias zshconfig="vim ~/.zshrc"
alias zshreload="source ~/.zshrc"
alias cat=ccat
alias delet=trash-put
alias vi=vim
alias c=clear
alias h="cd ~/"
