config:
  backup: true
  create: true
  banner: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_vs_settings.json:
    src: Code/User/settings.json
    dst: ~/.config/Code - OSS/User/settings.json
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    template: true
  f_spacemacs:
    src: spacemacs
    dst: ~/.spacemacs
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
profiles:
  dl-acer-1:
    dotfiles:
    - f_vimrc
    - f_vs_settings.json
    - f_zshrc
    - f_spacemacs
    - f_xresources
  dl-desk-1:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_vs_settings.json
    - f_spacemacs
