config:
  backup: true
  create: true
  banner: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_vs_settings.json:
    src: Code/User/settings.json
    dst: ~/.config/Code - OSS/User/settings.json
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zshrc_1:
    src: zshrc
    dst: ~/.zshrc
    template: true
profiles:
  st-mbp-1:
    dotfiles:
    - f_vimrc
    - f_vs_settings.json
    - f_zshrc
  dl-desk-1:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_vs_settings.json
